spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWK}
  datasource:
    driver-class-name: org.postgresql.Driver
    password: ${PWD}
    url: ${URL}
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
#      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        default_schema: wallet
        format_sql: true
    show-sql: true

